"""empty message

Revision ID: 0eea3e204b0e
Revises: 1043c7a0d69e
Create Date: 2023-05-18 15:18:39.557805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eea3e204b0e'
down_revision = '1043c7a0d69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_sequence')
    # ### end Alembic commands ###
