"""empty message

Revision ID: 1043c7a0d69e
Revises: 
Create Date: 2023-05-18 15:03:45.105607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1043c7a0d69e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('bar_code', sa.String(length=100),
                              autoincrement=True, nullable=False),
                    sa.Column('author', sa.String(length=100), nullable=False),
                    sa.Column('category', sa.String(length=100), nullable=False),
                    sa.Column('barcode_download_url', sa.String(
                        length=100), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_bar_code'), ['bar_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_book_category'),
                              ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_title'), ['title'], unique=False)

    op.create_table('student',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('registration_number', sa.String(
                        length=100), nullable=False),
                    sa.Column('class_name', sa.String(length=100), nullable=True),
                    sa.Column('grade', sa.String(length=100), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_registration_number'), [
                              'registration_number'], unique=True)

    op.create_table('loan',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('book_id', sa.Integer(), nullable=False),
                    sa.Column('loan_date', sa.DateTime(), nullable=False),
                    sa.Column('return_date', sa.DateTime(), nullable=False),
                    sa.Column('returned', sa.Boolean(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_student_id'),
                              ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_student_id'))
        batch_op.drop_index(batch_op.f('ix_loan_book_id'))

    op.drop_table('loan')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_registration_number'))
        batch_op.drop_index(batch_op.f('ix_student_name'))

    op.drop_table('student')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_title'))
        batch_op.drop_index(batch_op.f('ix_book_category'))
        batch_op.drop_index(batch_op.f('ix_book_bar_code'))
        batch_op.drop_index(batch_op.f('ix_book_author'))

    op.drop_table('book')
    # ### end Alembic commands ###
